# -*- coding: utf-8 -*-
"""FindLargestElement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHd8F6i6dK0gbUFPDD3JMqJuVcakJG6p
"""

def search(list):
  temp = 0
  for x in list:
    if temp <= x:
      largestValue = x
      temp = largestValue
  return largestValue

list = [1, 300, 2, 3, 4, 100, 5, 6, 60, 95, 30, 1000, 39, 1, 0, -1, 34, 28, 2991, 3940, 1]
search(list)